version: '3.5'

#================================================================================================
# NETWORK SETUP
#================================================================================================
networks:
  mynet-zeroc0d3:
    name: ${NETWORKS_NAME}
    driver: ${NETWORKS_DRIVER}
    ipam:
      config:
        - subnet: 172.111.112.0/16

#================================================================================================
# VOLUME SETUP
#================================================================================================
volumes:
  adminer:
    driver: ${VOLUMES_DRIVER}
  mariadb:
    driver: ${VOLUMES_DRIVER}
  portainer:
    driver: ${VOLUMES_DRIVER}

services:
#================================================================================================
# ADMINER
#================================================================================================
  adminer:
    image: dockerframework/adminer:latest
    container_name: ${CONTAINER_ADMINER}
    ports:
      - "${PORT_ADMINER}:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SESSION_ADMINER}:/sessions
    environment:
      - ADMINER_VERSION=${ADMINER_VERSION}
      - INSTALL_MSSQL=${INSTALL_MSSQL}
    privileged: true
    networks:
      mynet-zeroc0d3:
        ipv4_address: ${CONTAINER_IP_ADMINER}

#================================================================================================
# MARIADB
#================================================================================================
  mariadb:
    image: yobasystems/alpine-mariadb:${MARIADB_VERSION}
    container_name: ${CONTAINER_MARIADB}
    ports:
      - "${PORT_MARIADB}:3306"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_MARIADB}:/var/lib/mysql
    environment:
      - ENV=local
      - MYSQL_PROFILE=my-small
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=dbname
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
    privileged: true
    networks:
      mynet-zeroc0d3:
        ipv4_address: ${CONTAINER_IP_MARIADB}

#================================================================================================
# PORTAINER
#================================================================================================
  portainer:
    image: zerolabssyseng/portainer:latest
    container_name: ${CONTAINER_PORTAINER}
    ports:
      - "${PORT_PORTAINER}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PORTAINER}:/data
    environment:
      - PORTAINER_TEMPLATE=generic
      - PORTAINER_VERSION=${PORTAINER_VERSION}
    privileged: true
    networks:
      mynet-zeroc0d3:
        ipv4_address: ${CONTAINER_IP_PORTAINER}
