version: '3.5'

#================================================================================================
# NETWORK SETUP
#================================================================================================
networks:
  zeroc0d3-net:
    name: ${NETWORKS_NAME}
    driver: ${NETWORKS_DRIVER}
    ipam:
      config:
        - subnet: 172.119.119.0/16

#================================================================================================
# VOLUME SETUP
#================================================================================================
volumes:
  adminer:
    driver: ${VOLUMES_DRIVER}
  mariadb:
    driver: ${VOLUMES_DRIVER}
  portainer:
    driver: ${VOLUMES_DRIVER}

services:
#================================================================================================
# ADMINER
#================================================================================================
  adminer:
    image: dockerframework/adminer:latest
    container_name: ${CONTAINER_ADMINER}
    ports:
      - "${PORT_ADMINER}:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SESSION_ADMINER}:/sessions
    environment:
      - ADMINER_VERSION=${ADMINER_VERSION}
      - INSTALL_MSSQL=${INSTALL_MSSQL}
    privileged: true
    networks:
      zeroc0d3-net:
        ipv4_address: ${CONTAINER_IP_ADMINER}

#================================================================================================
# MARIADB
#================================================================================================
  mariadb:
    image: yobasystems/alpine-mariadb:${MARIADB_VERSION}
    container_name: ${CONTAINER_MARIADB}
    ports:
      - "${PORT_MARIADB}:3306"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_MARIADB}:/var/lib/mysql
    environment:
      - ENV=local
      - MYSQL_PROFILE=my-small                         # default configuration profile to use (my-small, my-medium ...)
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}   # root password (optional)
      - MYSQL_ROOT_HOST=${MARIADB_ROOT_HOST}           # root user hostmask (optional)
      - MYSQL_HOST=${MARIADB_HOST}                     # user hostmask
      - MYSQL_DATABASE=${MARIADB_DATABASE}             # create user database (optional)
      - MYSQL_USERNAME=${MARIADB_USERNAME}             # user name
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}             # user password
    privileged: true
    networks:
      zeroc0d3-net:
        ipv4_address: ${CONTAINER_IP_MARIADB}

#================================================================================================
# PORTAINER
#================================================================================================
  portainer:
    image: zerolabssyseng/portainer:latest
    container_name: ${CONTAINER_PORTAINER}
    ports:
      - "${PORT_PORTAINER}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PORTAINER}:/data
    environment:
      - PORTAINER_TEMPLATE=generic
      - PORTAINER_VERSION=${PORTAINER_VERSION}
    privileged: true
    networks:
      zeroc0d3-net:
        ipv4_address: ${CONTAINER_IP_PORTAINER}
